name: Upload Model to Hugging Face Hub

on:
  push:
    branches:
      - main  

jobs:
  upload-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install huggingface_hub

      - name: Upload to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          import os
          from huggingface_hub import HfApi
      
          api = HfApi()
          repo_id = "Ataur77/customer-query-classify"
          token = os.environ["HF_TOKEN"]
      
          api.create_repo(repo_id=repo_id, exist_ok=True, token=token)
          api.upload_folder(
              repo_id=repo_id,
              folder_path="customer-query-classify",
              path_in_repo="",
              token=token
          )
          api.upload_file(
              repo_id=repo_id,
              path_or_fileobj="README.md",
              path_in_repo="README.md",
              token=token
          )
        shell: python

